DROP TABLE IF EXISTS feedback;
DROP TABLE IF EXISTS participants;

CREATE TABLE participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    email TEXT,
    phone_number TEXT,
    team_name TEXT,
    is_present BOOLEAN DEFAULT FALSE
);


CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    participant_id BIGINT REFERENCES participants(id),
    rating INTEGER,
    liked TEXT,
    improvement TEXT
);

INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Rahul kumar sharma', 'rahul.sharma15855@gmail.com', '+917668073420', 'hacks', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('atul sharma', 'rks.rahul10890@gmail.com', '7417073420', 'hacks', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Mansi Garg', 'mansigarg1903@gmail.com', '+917888344909', 'LonerPenguin', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Ashbin Saji', 'sajiashbin17@gmail.com', '+917091533993', NULL, FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Gautam Bijarniya', 'gautambijarniya10@gmail.com', '+918949303957', 'Gautam Bijarniya', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Aditya singh', 'optimistotaku@gmail.com', '+918588873787', 'Interrnal pointerr varriable', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Ruhani Gill', 'ruhanigill194@gmail.com', '7814115368', 'Interrnal pointerr varriable', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Saima', 'saimaalauddin79@gmail.com', '+917065859486', 'coder', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('aditya', 'sheikhsaima2787@gmail.com', '7065859486', 'coder', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Abdurrahman Khan', 'abdurrahmanark21@gmail.com', '+919911683752', 'Hackwarriors', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Saurav sharma', 'isauravsharmaokay4359@gmail.com', '+919771803139', 'NoMan', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Saurav Sharma', 'isauravsharmaokay4359@gmail.com', '9771803139', 'NoMan', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Tejas Lamba', 'tejas22feb@gmail.com', '+919873706397', 'Syntax Terror', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Kunal Jain', 'shivaay381999@gmail.com', '+918287349924', 'Two Pointers', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Rashmi Bishen', 'rashmibishen22@gmail.com', '8743075965', 'Two Pointers', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('shubham bansiwal', 'shubhambansiwal@codeblish.com', '+917840891695', 'highenddevelopers', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Dhruv Sharma', 'dhruv2000sharma@gmail.com', '+919899620898', 'Team', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Rudra Bounthiyal', 'rudrabounthiyal@gmail.com', '+919871014699', 'Rudra', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Ryan Narula', 'ryannarula@gmail.com', '+919818556694', 'Cyber defender', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Jornas Haobijam', 'haobijamjornas@gmail.com', '+918837315062', 'Blitzkrieg', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Chinmoy Goswami', 'chinmoygoswami4323@gmail.com', '9387313721', 'Blitzkrieg', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Sujal Kalauni', 'sujal.kalauni@s.amity.edu', '+918273983822', 'Blastoise', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Garvit', 'Garvit2@s.amity.edu', '86078 81760', 'Blastoise', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Apoorv Mittal', 'mittalapoorv2004@gmail.com', '+918700558594', 'Apoorv with DSA', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('NA', 'NA', 'NA', 'Apoorv with DSA', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('ANSH PANDYA', 'dransh.pandyaking@gmail.com', '+918010145997', 'Robin Hood gang', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Ashutosh Panda', 'pandaashutosh808@gmail.com', '9654538501', 'Robin Hood gang', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Kandepu Harsha venkata Ratna Chowdary', 'harsha.kandepu05@gmail.com', '+917981346319', 'Duohacks', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Vallabhaneni Teja Veera Satya Sri Narendra', 'Vallabhaneniteja1818@gmail.com', '+91 63002 24575', 'Duohacks', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Yash Jindal', 'jindal.yash18@gmail.com', '+919871024684', 'Team-Yash', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Anish Kumar singh', 'anishaksingh205@gmail.com', '+917065253400', 'Codem', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Bhoomi Rustagi', 'bhoomirustagi27@gmail.com', '+919310170655', 'Team Rush', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Shivang Rai', 'shivangr80@gmail.com', '+918467087157', 'Team Rush', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Viraj Panchal', 'n.panchal4@gmail.com', '+918178604845', 'Rizzlers', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Utkarsh', NULL, '+918178604845', 'Rizzlers', FALSE);
INSERT INTO participants (name, email, phone_number, team_name, is_present) VALUES ('Uma Ghildiyal', 'ghildiyaluma0@gmail.com', NULL, NULL, FALSE);